// truffle-config.js — CargoChain
// Active: Ganache on 127.0.0.1:7545, chainId 1337, network_id *.
// Future plan: Sepolia (commented below — do NOT enable in v1).

require('dotenv').config();
const HDWalletProvider = require('@truffle/hdwallet-provider');

module.exports = {
  networks: {
    development: {
      host: process.env.GANACHE_HOST || '127.0.0.1',
      port: Number(process.env.GANACHE_PORT || 7545),
      network_id: Number(process.env.GANACHE_NETWORK_ID || 1337),
    },

    // =========================================================================
    // FUTURE PLAN — Sepolia testnet
    // -------------------------------------------------------------------------
    // Not part of v1. The team has explicitly deferred Sepolia to a later
    // milestone. To activate, uncomment the block below, fill in `.env`
    // (SEPOLIA_RPC, TEAM_MNEMONIC), and run:
    //   npx truffle migrate --network sepolia
    // =========================================================================
    // sepolia: {
    //   provider: () => new HDWalletProvider(
    //     process.env.TEAM_MNEMONIC,
    //     process.env.SEPOLIA_RPC,
    //   ),
    //   network_id: 11155111,
    //   confirmations: 2,
    // },
  },

  contracts_directory: './contracts',
  contracts_build_directory: './build/contracts',

  compilers: {
    solc: {
      version: '0.8.35',
      settings: {
        viaIR: true,
        // Keep generated bytecode compatible with Ganache/Truffle's test EVM.
        // Newer solc defaults can emit opcodes that older local EVM settings
        // report as "invalid opcode" during view calls.
        evmVersion: 'paris',
        optimizer: {
          enabled: true,
          // Favor deployed bytecode size: CargoChain is a demo DApp whose
          // escrow contract has a broad, intentionally readable API surface.
          runs: 1,
        },
      },
    },
  },

  mocha: {
    timeout: 60000, // Ganache deploy + time-travel tests can take longer than default
  },
};
